AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Exclude:
    - 'Rakefile'

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/SingleLineMethods:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
