---
cog_bundle_version: 4
name: jumpcloud
description: Commands for interacting with JumpCloud
version: 0.4.3
homepage: https://github.com/davejlong/cog-jumpcloud
author: Dave Long <dlong@cagedata.com>
docker:
  image: davejlong/cog-jumpcloud
  tag: 0.4.3
permissions:
  - jumpcloud:read
  - jumpcloud:write
config:
  env:
    - var: JUMPCLOUD_API_KEY
      description: API Key for JumpCloud
  notes: |
    Want to manage multiple JumpCloud accounts? Setup multiple API keys by
    appending an alias after `JUMPCLOUD_API_KEY` like
    `JUMPCLOUD_API_KEY_EXAMPLE`. All commands support the `account` option to
    select the account:

      ```
      jumpcloud:users --account example
      jumpcloud:systems --account example
      ```

    Get a list of configured account with:

      ```
      jumpcloud:accounts
      ```

commands:
  accounts:
    executable: "/home/bundle/cog-command"
    description: get a list of accounts that can be used for the `--account` option
    rules:
      - must have jumpcloud:read
    examples: |
      jumpcloud:accounts
  users:
    executable: "/home/bundle/cog-command"
    description: Commands for working with users
    subcommands:
      list: List all users (default)
      create: Create a new user
      get: Get a tag
    rules:
      - must have jumpcloud:read
      - with arg[0] == 'create' must have jumpcloud:write
    options:
      account:
        type: string
        required: false
        short_flag: a
        description: Account to query
      email:
        type: string
        required: false
        short_flag: e
        description: Required for `create`. Email address of new user
      username:
        type: string
        required: false
        short_flag: e
        description: Required for `create`. Username of new user
      id:
        type: string
        required: false
        short_flag: i
        description: Required for `get`. ID of user to retrieve
      limit:
        type: int
        required: false
        description: Used with `list`. Limit number of results returned. Default 10
      skip:
        type: int
        required: false
        description: Used with `list`. Skip number of results. Default 0
    examples: |
      jumpcloud:users list

      jumpcloud:users get --id 58ac62df263162b92bfds32bf

      jumpcloud:users create --email dlong@cagedata.com --username dlong
  systems:
    executable: "/home/bundle/cog-command"
    description: Commands for working with systems
    subcommands:
      list: List all systems (default)
      get: Get information about a system
    rules:
      - must have jumpcloud:read
    options:
      account:
        type: string
        required: false
        short_flag: a
        description: Account to query
      id:
        type: string
        required: false
        short_flag: i
        description: Required for `get`. System ID to retrieve
      limit:
        type: int
        required: false
        description: Used with `list`. Limit number of results returned. Default 10
      skip:
        type: int
        required: false
        description: Used with `list`. Skip number of results. Default 0
    examples: |
      jumpcloud:systems list

      jumpcloud:systems get --id 58ac62df263162b92bfds32bf
  tags:
    executable: "/home/bundle/cog-command"
    description: Commands for working with tags
    subcommands:
      list: List all tags (default)
      get: Get a tag
    rules:
      - must have jumpcloud:read
    options:
      account:
        type: string
        required: false
        short_flag: a
        description: Account to query
      id:
        type: string
        required: false
        short_flag: i
        description: Required for `get`. Tag ID to retrieve
      limit:
        type: int
        required: false
        description: Used with `list`. Limit number of results returned. Default 10
      skip:
        type: int
        required: false
        description: Used with `list`. Skip number of results. Default 0
    examples: |
      jumpcloud:tags list

      jumpcloud:tags get --id 58ac62df263162b92bfds32bf
  commands:
    executable: "/home/bundle/cog-command"
    description: Commands for working with JumpCloud Commands
    subcommands:
      list: List all commands (default)
      get: Get a commands
    rules:
      - must have jumpcloud:read
    options:
      account:
        type: string
        required: false
        short_flag: a
        description: Account to query
      id:
        type: string
        required: false
        short_flag: i
        description: Required for `get`. Command ID to retrieve
      limit:
        type: int
        required: false
        description: Used with `list`. Limit number of results returned. Default 10
      skip:
        type: int
        required: false
        description: Used with `list`. Skip number of results. Default 0
    examples: |
      jumpcloud:commands list

      jumpcloud:commands get --id 58ac62df263162b92bfds32bf
  results:
    executable: "/home/bundle/cog-command"
    description: Commands for querying command results
    subcommands:
      list: List all command results (default)
      get: Get a command result
    rules:
      - must have jumpcloud:read
    options:
      account:
        type: string
        required: false
        short_flag: a
        description: Account to query
      id:
        type: string
        required: false
        short_flag: i
        description: Required for `get`. Command Result ID to retrieve
      limit:
        type: int
        required: false
        description: Used with `list`. Limit number of results returned. Default 10
      skip:
        type: int
        required: false
        description: Used with `list`. Skip number of results. Default 0
    examples: |
      jumpcloud:results list

      jumpcloud:results get --id 58ac62df263162b92bfds32bf
templates:
  users:
    body: |
      | ID  | Username | Email | Name | Account Locked |
      | --- | -------- | ----- | ---- | -------------- |
      ~each var=$results~
      | ~$item.id~ | ~$item.username~ | ~$item.email~ | ~$item.lastname~, ~$item.firstname~ | ~$item.account_locked~ |
      ~end~
  systems:
    body: |
      | ID  | Hostname | Serial Number | OS  | Last Contact | Active |
      | --- | -------- | ------------- | --- | ------------ | ------ |
      ~each var=$results~
      | ~$item.id~ | ~$item.hostname~ | ~$item.serialNumber~ | ~$item.os~ ~$item.version~ | ~$item.ipList~ | ~$item.lastContact~ | ~$item.active~ |
      ~end~
  tags:
    body: |
      | ID  | Name |
      | --- | ---- |
      ~each var=$results~
      | ~$item.id~ | ~$item.name~ |
      ~end~
  commands:
    body: |
      | ID  | Name | Schedule | Command |
      | --- | ---- | -------- | ------- |
      ~each var=$results~
      | ~$item.id~ | ~$item.name~ | ~$item.schedule~ | ~$item.command~ |
      ~end~
  command_results:
    body: |
      | ID  | Command | System | User | Time |
      | --- | ------- | ------ | ---- | ---- |
      ~each var=$results~
      | ~$item.id~ | ~$item.command_id~ | ~$item.system~ | ~$item.user~ | ~$item.responseTime~ |
      ~end~
